services:
  backend:
    build: .
    container_name: parser_app
    restart: always
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/parserdb
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
    volumes:
      - ./logs:/app/logs 
    ports:
      - "8000:8000" 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: parser_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
